name: CI

on:
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHPStan (max level)
        run: vendor/bin/phpstan analyse --level=max --configuration=phpstan.neon --baseline=phpstan-baseline.neon

  cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Check coding style
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --config=.php-cs-fixer.dist.php

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHPUnit
        run: vendor/bin/phpunit

  mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run Infection
        run: vendor/bin/infection --min-msi=70 --threads=2 --coverage=coverage --log-verbosity=all